name: 🐛 Bug Report
description: Report a bug to help us improve the guide.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce it?
      description: List the steps to reproduce the behavior.
      placeholder: |
        1. Open file '...'
        2. Run command '...'
        3. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Git Version
      description: What version of Git are you using? (git --version)
    validations:
      required: false
